"""
English language translation
"""
en = {
    "projectname": "SICLIFE",
    "wrong_username": "Wrong username or password.",
    "login_successful": "Login sucessful.",
    "record_successful": "Record sucessfully retrieved.",
    "blocked_account": "Sorry your account has been blocked. Kindly contact your administrator.",
    "data_retrived": "Data retrived successfully.",
    "menu_home": "HOME",
	"menu_customer_uploads": "CUSTOMER UPLOADS",
	"menu_dashboard": "DASHBOARD",
	"menu_transactions": "ACTIVITIES",
	"menu_admins": "ADMINISTRATORS",
    "menu_validators": "VALIDATORS",
	"menu_customers": "SERIALS",
    "menu_merchants": "MERCHANTS",
    "menu_logs": "LOGS",
    "menu_settings": "SETTINGS",
    "menu_account": "VA ACCOUNTS",
    "not_submitted": "Not Submitted",
    "submitted": "Submitted",
    "Declined": "Declined",
    "approved": "Approved",
    "corrupt_file": "Corrupted File",
    "not_processed": "Not Processed",
    "initiated": "Initiated",
    "failed": "Failed",
    "success": "Success",
    "unknown": "Unknown",
    "branch_add_modal_label":"Add Branch",
    "branch_add_btn": "Add Branch",
    "active": "Active",
    "inactive": "Inactive",
    "validator_added": "Validator added successfully.",
    "validator_add_fail": "Failed to add validator.",
    "validator_delete_fail": "Failed to delete validator.",
    "validator_deleted": "Validator deleted successfully.",
    "validator_updated": "Validator updated successfully.",
    "validator_update_fail": "Failed to update validator.",
    "wrong_file_format": "Wrong file format.",
    "file_recorded": "File upload sucessful.",
    "existing_admin": "Username is already in using. Kindly choose another.",
    "existing_Institution": "Short name is already in using. Kindly choose another.",
    "admin_added": "Administrator added successfully.",
    "admin_add_fail": "Failed to add administrator.",
    "admin_updated": "Administrator updated successfully.",
    "admin_update_failed": "Failed to update administrator.",
    "password_mismatch": "Passwords don't match.",
    "wrong_old_password": "Wrong current password provided.",
    "admin_sucessful_pass_change": "Password changed successfully.",
    "unauthorised_op": "Unauthorised Opteration",
    "file_decline_failed": "Failed to decline payment. Kindly try again later.",
    "file_decline_successful": "Successfully declined payment.",
    "file_approval_failed": "Failed to approve payment. Kindly try again later.",
    "file_approval_successful": "Successfully approved payment.",
    "failed_account_creation": "Could not create merchant virtual account. kindly try again later.",
    "merchant_added": "Merchant Added successfully.",
    "topup_requested": "Topup Request pending. Kindly pay amount using provided payment token.",
    "topup_requested_failed": "Topup request failed. Kindly try again later.",
    "topup_requested_processed": "Topup request processed",
    "topup_modal_label": "BULKPAY ACCOUNT TOPUP",
    "topup_manilla_label": "Manilla",
    "topup_bank_label": "Bank Payment",
    "fullname_label":"Full Name",
    "email_label":"Email",
    "amount_label":"Amount",
    "payment_token_label":"Payment Token",
    "bank_label": "Bank",
    "mode_label": "Mode",
    "cash_label": "Cash",
    "cheque_label": "Cheque",
    "transfer_label": "Transfer",
    "username_label": "Username",
    "btn_topup_account_label": "Topup Account",
    "profile_modal_label": "PROFILE",
    "msisdn_label": "Phone Number",
    "current_password_label": "Current Password",
    "new_password_label": "New Password",
    "repeat_password_label": "Retype Password",
    "btn_change_password_label": "Change Password",
    "filter_lable": "Filter",
    "of_lable": "of",
    "tbl_bulkid_head":"BULK ID.",
    "tbl_file_name_head":"FILE NAME",
    "tbl_size_head":"SIZE",
    "tbl_app_status_head":"APPROVAL STATUS",
    "tbl_processing_status_head":"PROCESSING STATUS",
    "tbl_uploaded_by_head":"UPLOADED BY",
    "tbl_uploaded_by_branch":"BRANCH",
    "tbl_upload_date_head":"UPLOAD DATE",
    "tbl_action_head":"ACTION",
    "upload_add_file_label": "Add file",
    "upload_label": "Upload",
    "upload_cancel_label": "Cancel Upload",
    "upload_file_type_label": "FILE TYPE",
    "pay_details_modal_label": "Payment details",
    "pay_details_info_label": "Info",
    "pay_details_approval_label": "Approvals",
    "pay_details_label": "Details",
    "pay_details_bulkid_label": "BULK ID",
    "pay_details_filename_label": "FILE NAME",
    "pay_details_appstatus_label": "APPROVAL STATUS",
    "pay_details_proststatus_label": "PROCESSING STATUS",
    "pay_details_currency_label": "CURRENCY",
    "pay_details_amount_label": "AMOUNT",
    "pay_details_username_label": "USERNAME",
    "pay_details_level_label": "USER LEVEL",
    "pay_details_response_label": "RESPONSE",
    "pay_details_date_label": "DATE",
    "pay_details_remarks_label": "REMARKS",
    "bulk_dowload": "Download File",
    "bulk_decline": "Decline",
    "bulk_approve": "Approve",
    "start_date": "from",
    "end_date": "to",
    "bulk_opt_app_status": "Approval Status",
    "bulk_opt_all": "All",
    "bulk_opt_submit": "Submitted",
    "bulk_opt_decline": "Declined",
    "bulk_opt_approve": "Approved",
    "bulk_opt_corrupt_file": "Corrupt File",
    "bulk_opt_pro_status": "Processing Status",
    "bulk_opt_not_proce": "Not Processed",
    "bulk_opt_initiate": "Initiated",
    "bulk_opt_failed": "Failed",
    "bulk_opt_success": "Success",
    "bulk_opt_export": "Export",
    "bulk_opt_filter": "Filter",
    "dash_total_amount_label": "Total amount",
    "dash_amount_success_label": "Total amount successful",
    "dash_amount_failed_label": "Total amount failed",
    "dash_analyse_label": "Analyse",
    "dash_analyse_Desc_label": "By Date",
    "dash_analyse_bnt": "Analyse",
    "trans_tbl_id_head": "TRANSACTION ID.",
    "trans_tbl_ref_head": "FUSION REF. ID",
    "trans_tbl_bulkid_head": "BULK ID",
    "trans_tbl_recv_head": "RECEIVING HSE",
    "trans_tbl_userid_head": "RECEIVING USER ID",
    "trans_tbl_amt_head": "AMOUNT",
    "trans_tbl_status_head": "STATUS",
    "trans_tbl_status_head": "STATUS DETAILS",
    "trans_tbl_exe_head": "EXECUTION TIME",
    "tbl_bulk_details": "Details",
    "filter_status": "Status",
    "opt_uploader": "Uploader",
    "opt_approver1": "Approver1",
    "opt_approver2": "Approver2",
    "opt_approver3": "Approver3",
    "opt_approver4": "Approver4",
    "opt_approver5": "Approver5",
    "approver_level_label": "Approver Level",
    "bulk_active": "Active",
    "bulk_deactivate": "Deactivated",
    "search_lable": "Search for ...",
    "admin_tbl_username": "USERNAME",
    "admin_tbl_fname": "FIRST NAME",
    "admin_tbl_lname": "LAST NAME",
    "admin_tbl_email": "EMAIL",
    "admin_tbl_msisdn": "PHONE NUMBER",
    "admin_tbl_inst": "INSTITUTION",
    "admin_tbl_utype": "USER TYPE",
    "admin_tbl_status": "STATUS",
    "admin_tbl_cdate": "DATE CREATED",
    "admin_tbl_acttion": "ACTION",
    "admin_add_modal_title": "Add Admin",
    "validator_add_modal_title": "Add Validator",
    "admin_modify_modal_title": "Update Admin",
    "admin_add_modal_label": "Add Admin",
    "firstname_label": "First Name",
    "lastname_label": "Last Name",
    "username_label": "Username",
    "msisdn_label": "Phone Number",
    "email_label": "Email",
    "usertype_label": "User Type",
    "opt_reveiwer": "Reviewer",
    "opt_administrator": "Administrator",
    "institution_label": "Institution",
    "admin_add_btn": "Add Admin. ",
    "admin_modify_btn": "Update Admin",
    "btn_deactivate_label": "Deactivate",
    "btn_activate_label": "Activate",
    "pie_chart_title": "Number of Transaction Per Institution",
    "bar_chart_title": "Amount Transafered Per Institution",
    "inst_tbl_instname": "INISTITUION NAME",
    "inst_tbl_inst_shortname": "SHORT NAME",
    "inst_tbl_desc": "DESCRIPTION",
    "inst_tbl_createdby": "CREATED BY",
    "inst_tbl_status": "STATUS",
    "inst_tbl_regdate": "DATE REGISTERED",
    "inst_tbl_action": "ACTION",
    "inst_add_label": "Add Institution",
    "inst_add_modal_title": "Add Institution",
    "inst_name_label": "Name",
    "inst_short_name_labe": "Short Name",
    "inst_desc_label": "Description",
    "inst_type_label": "Type",
    "inst_type_opt_bank": "BANK",
    "inst_type_opt_wallet": "WALLET",
    "inst_add_btn_label": "Add Institution",
    "inst_modify_modal_title": "Update Institution",
    "inst_modify_btn_label": "Update Institution",
    "merch_tbl_name": "MERCHANT NAME",
    "merch_tbl_shortname": "SHORT NAME",
    "merch_tbl_cname": "CONTACT NAME",
    "merch_tbl_adacc": "ADMIN ACCOUNT",
    "merch_tbl_cmsisdn": "PHONE NUMBER",
    "merch_tbl_bpacc": "BULKPAY ACC.",
    "merch_tbl_acc_balance": "ACC. BALANCE",
    "merch_tbl_app_required": "APPROVAL REQUIRED",
    "merch_tbl_status": "STATUS",
    "merch_tbl_reg_date": "DATE REGISTERED",
    "merch_tbl_action": "ACTION",
    "customer_add_label": "Add Customer",
    "merch_modal_title": "Add Merchant",
    "merch_name_label": "Name",
    "merch_shortname_label": "Short Name",
    "merch_desc_label": "Dercription",
    "merch_cfname_label": "Contact First Name",
    "merch_clname_label": "Contact Last Name",
    "merch_cmsisdn_label": "Contact Phone Number",
    "merch_cemail_label": "Contact Email",
    "merch_adusername_label": "Administrator Username",
    "merch_app_num_label": "Number of Approvers",
    "merch_add_btn_label": "Add Merchant",
    "merch_modify_modal_title":"Edit Merchant",
    "merch_modify_btn_title":"Update Merchant",
    "topup_tbl_tpid": "TOPUP ID",
    "topup_tbl_tpby": "TOPUP BY",
    "topup_tbl_tpamount": "AMOUNT",
    "topup_tbl_tpamountbf": "AMOUNT BEFORE",
    "topup_tbl_tpamountaf": "AMOUNT AFTER",
    "topup_tbl_tpchannel": "CHANNEL",
    "topup_tbl_tpdate": "DATE",
    "topup_account_topup":"Topup Account",
    "topup_back_to_topup":"Back to Topups",
    "topup_pending_topup":"Pending Topups",
    "pending_tbl_tokenid": "TOKEN ID",
    "pending_tbl_requestedby": "REQUESTED BY",
    "pending_tbl_amount": "AMOUNT",
    "pending_tbl_paymentmet": "PAYMENT MODE",
    "pending_tbl_institution": "INSTITUTION",
    "pending_tbl_app_status": "APPROVAL STATUS",
    "pending_tbl_fin_app": "FIRST APPROVAL",
    "pending_tbl_opt_app": "SECOND APPROVAL",
    "pending_tbl_date": "DATE",
    "pending_tbl_action": "ACTION",
    "pending_cancel": "Cancel",
    "pending_approve": "Approve",
    "pending_decline": "Decline",
    "pending_confirm": "Confirm",
    "pending_no_action": "No Action",
    "confirm_topup_title": "Confirmation",
    "topup_cb_transaction_id": "TRANSACTION ID",
    "topup_cb_manilla_ref": "REFRENCE ID",
    "topup_cb_amount": "AMOUNT",
    "topup_cb_chanel": "CHANNEL USED",
    "topup_cb_status": "STATUS",
    "admin_pass_reset_successful":"A new password has been generated and sent to ",
    "admin_pass_reset_failed":"Failed to reset password.",
    "pay_details_charge_label":"EXTRA CHARGES",
    "insufficient_balance": "Sorry you account balance is low. Kindly topup to proceed.",

    "customer_id": "Customer ID",
    "customer_account": "Acc. Number",
    "customer_fname": "First Name",
    "customer_mname": "Middle Name",
    "customer_lame": "Last Name",
    "customer_sex": "Gender",
    "customer_product": "Product",
    "customer_wallet": "Wallet",
    "customer_withd_status": "Withdrawal Status",
    "customer_deposit_status": "deposit Status",
    "customer_acc_balance": "Balance",
    "customer_status": "Status",
    "customer_reg_date": "Registration Date",
    "customer_details": "Details",
    "cutomer_modify_modal_title": "Customer Details",
}


"""
French language translation
"""
fr = {
    "projectname": "BulkPay",
    "wrong_username": "Wrong username or password.",
    "login_successful": "Login sucessful.",
    "blocked_account": "Sorry your account has been blocked. Kindly contact your administrator.",
    "data_retrived": "Data retrived successfully.",
    "menu_home": "HOME",
    "menu_customer_uploads": "BULK PAY",
    "menu_dashboard": "DASHBOARD",
    "menu_transactions": "TRANSACTIONS",
    "menu_admins": "ADMINISTRATORS",
    "menu_topup": "TOPUPS",
    "menu_institutions": "INSTITUTIONS",
    "menu_merchants": "MERCHANTS",
    "not_submitted": "Not Submitted",
    "submitted": "Submitted",
    "Declined": "Declined",
    "approved": "Approved",
    "corrupt_file": "Corrupted File",
    "not_processed": "Not Processed",
    "initiated": "Initiated",
    "failed": "Failed",
    "success": "Success",
    "unknown": "Unknown",
    "active": "Active",
    "inactive": "Inactive",
    "wrong_file_format": "Wrong file format.",
    "file_recorded": "File upload sucessful.",
    "existing_admin": "Username is already in using. Kindly choose another.",
    "existing_Institution": "Short name is already in using. Kindly choose another.",
    "admin_added": "Administrator added successfully.",
    "admin_add_fail": "Failed to add administrator.",
    "admin_updated": "Administrator updated successfully.",
    "admin_update_failed": "Failed to update administrator.",
    "password_mismatch": "Passwords don't match.",
    "wrong_old_password": "Wrong current password provided.",
    "admin_sucessful_pass_change": "Password changed successfully.",
    "unauthorised_op": "Unauthorised Opteration",
    "file_decline_failed": "Failed to decline payment. Kindly try again later.",
    "file_decline_successful": "Successfully declined payment.",
    "file_approval_failed": "Failed to approve payment. Kindly try again later.",
    "file_approval_successful": "Successfully approved payment.",
    "failed_account_creation": "Could not create merchant virtual account. kindly try again later.",
    "merchant_added": "Merchant Added successfully.",
    "topup_requested": "Topup Request pending. Kindly pay amount using provided payment token.",
    "topup_requested_failed": "Topup request failed. Kindly try again later.",
    "topup_requested_processed": "Topup request processed",
    "topup_modal_label": "BULKPAY ACCOUNT TOPUP",
    "topup_manilla_label": "Manilla",
    "topup_bank_label": "Bank Payment",
    "fullname_label":"Full Name",
    "email_label":"Email",
    "amount_label":"Amount",
    "payment_token_label":"Payment Token",
    "bank_label": "Bank",
    "mode_label": "Mode",
    "cash_label": "Cash",
    "cheque_label": "Cheque",
    "transfer_label": "Transfer",
    "username_label": "Username",
    "btn_topup_account_label": "Topup Account",
    "profile_modal_label": "PROFILE",
    "msisdn_label": "Phone Number",
    "current_password_label": "Current Password",
    "new_password_label": "New Password",
    "repeat_password_label": "Retype Password",
    "btn_change_password_label": "Change Password",
    "filter_lable": "Filter",
    "of_lable": "of",
    "tbl_bulkid_head":"BULK ID.",
    "tbl_file_name_head":"FILE NAME",
    "tbl_size_head":"SIZE",
    "tbl_app_status_head":"APPROVAL STATUS",
    "tbl_processing_status_head":"PROCESSING STATUS",
    "tbl_uploaded_by_head":"UPLOADED BY",
    "tbl_upload_date_head":"UPLOAD DATE",
    "tbl_action_head":"ACTION",
    "upload_add_file_label": "Add file",
    "upload_label": "Upload",
    "upload_cancel_label": "Cancel Upload",
    "upload_file_type_label": "FILE TYPE",
    "pay_details_modal_label": "Payment details",
    "pay_details_info_label": "Info",
    "pay_details_approval_label": "Approvals",
    "pay_details_bulkid_label": "BULK ID",
    "pay_details_filename_label": "FILE NAME",
    "pay_details_appstatus_label": "APPROVAL STATUS",
    "pay_details_proststatus_label": "PROCESSING STATUS",
    "pay_details_currency_label": "CURRENCY",
    "pay_details_amount_label": "AMOUNT",
    "pay_details_username_label": "USERNAME",
    "pay_details_level_label": "USER LEVEL",
    "pay_details_response_label": "RESPONSE",
    "pay_details_date_label": "DATE",
    "pay_details_remarks_label": "REMARKS",
    "bulk_dowload": "Download File",
    "bulk_decline": "Decline",
    "bulk_approve": "Approve",
    "start_date": "from",
    "end_date": "to",
    "bulk_opt_app_status": "Approval Status",
    "bulk_opt_all": "All",
    "bulk_opt_submit": "Submitted",
    "bulk_opt_decline": "Declined",
    "bulk_opt_approve": "Approved",
    "bulk_opt_corrupt_file": "Corrupt File",
    "bulk_opt_pro_status": "Processing Status",
    "bulk_opt_not_proce": "Not Processed",
    "bulk_opt_initiate": "Initiated",
    "bulk_opt_failed": "Failed",
    "bulk_opt_success": "Success",
    "bulk_opt_export": "Export",
    "bulk_opt_filter": "Filter",
    "dash_total_amount_label": "Total amount",
    "dash_amount_success_label": "Total amount successful",
    "dash_amount_failed_label": "Total amount failed",
    "dash_analyse_label": "Analyse",
    "dash_analyse_Desc_label": "By Date",
    "dash_analyse_bnt": "Analyse",
    "trans_tbl_id_head": "TRANSACTION ID.",
    "trans_tbl_ref_head": "FUSION REF. ID",
    "trans_tbl_bulkid_head": "BULK ID",
    "trans_tbl_recv_head": "RECEIVING HSE",
    "trans_tbl_userid_head": "RECEIVING USER ID",
    "trans_tbl_amt_head": "AMOUNT",
    "trans_tbl_status_head": "STATUS",
    "trans_tbl_status_head": "STATUS DETAILS",
    "trans_tbl_exe_head": "EXECUTION TIME",
    "tbl_bulk_details": "Details",
    "filter_status": "Status",
    "opt_uploader": "Uploader",
    "opt_approver1": "Approver1",
    "opt_approver2": "Approver2",
    "opt_approver3": "Approver3",
    "opt_approver4": "Approver4",
    "opt_approver5": "Approver5",
    "approver_level_label": "Approver Level",
    "bulk_active": "Active",
    "bulk_deactivate": "Deactivated",
    "search_lable": "Search for ...",
    "admin_tbl_username": "USERNAME",
    "admin_tbl_fname": "FIRST NAME",
    "admin_tbl_lname": "LAST NAME",
    "admin_tbl_email": "EMAIL",
    "admin_tbl_msisdn": "PHONE NUMBER",
    "admin_tbl_inst": "INSTITUTION",
    "admin_tbl_utype": "USER TYPE",
    "admin_tbl_status": "STATUS",
    "admin_tbl_cdate": "DATE CREATED",
    "admin_tbl_acttion": "ACTION",
    "admin_add_modal_title": "Add Admin",
    "admin_modify_modal_title": "Update Admin",
    "admin_add_modal_label": "Add Admin",
    "firstname_label": "First Name",
    "lastname_label": "Last Name",
    "username_label": "Username",
    "msisdn_label": "Phone Number",
    "email_label": "Email",
    "usertype_label": "User Type",
    "opt_reveiwer": "Reviewer",
    "opt_administrator": "Administrator",
    "institution_label": "Institution",
    "admin_add_btn": "Add Admin. ",
    "validator_add_btn": "Add Validator. ",
    "admin_modify_btn": "Update Admin",
    "btn_deactivate_label": "Deactivate",
    "btn_activate_label": "Activate",
    "pie_chart_title": "Number of Transaction Per Institution",
    "bar_chart_title": "Amount Transafered Per Institution",
    "inst_tbl_instname": "INISTITUION NAME",
    "inst_tbl_inst_shortname": "SHORT NAME",
    "inst_tbl_desc": "DESCRIPTION",
    "inst_tbl_createdby": "CREATED BY",
    "inst_tbl_status": "STATUS",
    "inst_tbl_regdate": "DATE REGISTERED",
    "inst_tbl_action": "ACTION",
    "inst_add_label": "Add Institution",
    "inst_add_modal_title": "Add Institution",
    "inst_name_label": "Name",
    "inst_short_name_labe": "Short Name",
    "inst_desc_label": "Description",
    "inst_type_label": "Type",
    "inst_type_opt_bank": "BANK",
    "inst_type_opt_wallet": "WALLET",
    "inst_add_btn_label": "Add Institution",
    "inst_modify_modal_title": "Update Institution",
    "inst_modify_btn_label": "Update Institution",
    "merch_tbl_name": "MERCHANT NAME",
    "merch_tbl_shortname": "SHORT NAME",
    "merch_tbl_cname": "CONTACT NAME",
    "merch_tbl_adacc": "ADMIN ACCOUNT",
    "merch_tbl_cmsisdn": "PHONE NUMBER",
    "merch_tbl_bpacc": "BULKPAY ACC.",
    "merch_tbl_acc_balance": "ACC. BALANCE",
    "merch_tbl_app_required": "APPROVAL REQUIRED",
    "merch_tbl_status": "STATUS",
    "merch_tbl_reg_date": "DATE REGISTERED",
    "merch_tbl_action": "ACTION",
    "merch_add_label": "Add Merchant",
    "merch_modal_title": "Add Merchant",
    "merch_name_label": "Name",
    "merch_shortname_label": "Short Name",
    "merch_desc_label": "Dercription",
    "merch_cfname_label": "Contact First Name",
    "merch_clname_label": "Contact Last Name",
    "merch_cmsisdn_label": "Contact Phone Number",
    "merch_cemail_label": "Contact Email",
    "merch_adusername_label": "Administrator Username",
    "merch_app_num_label": "Number of Approvers",
    "merch_add_btn_label": "Add Merchant",
    "merch_modify_modal_title":"Edit Merchant",
    "merch_modify_btn_title":"Update Customer",
    "topup_tbl_tpid": "TOPUP ID",
    "topup_tbl_tpby": "TOPUP BY",
    "topup_tbl_tpamount": "AMOUNT",
    "topup_tbl_tpamountbf": "AMOUNT BEFORE",
    "topup_tbl_tpamountaf": "AMOUNT AFTER",
    "topup_tbl_tpchannel": "CHANNEL",
    "topup_tbl_tpdate": "DATE",
    "topup_account_topup":"Topup Account",
    "topup_back_to_topup":"Back to Topups",
    "topup_pending_topup":"Pending Topups",
    "pending_tbl_tokenid": "TOKEN ID",
    "pending_tbl_requestedby": "REQUESTED BY",
    "pending_tbl_amount": "AMOUNT",
    "pending_tbl_paymentmet": "PAYMENT MODE",
    "pending_tbl_institution": "INSTITUTION",
    "pending_tbl_app_status": "APPROVAL STATUS",
    "pending_tbl_fin_app": "FIRST APPROVAL",
    "pending_tbl_opt_app": "SECOND APPROVAL",
    "pending_tbl_date": "DATE",
    "pending_tbl_action": "ACTION",
    "pending_cancel": "Cancel",
    "pending_approve": "Approve",
    "pending_decline": "Decline",
    "pending_confirm": "Confirm",
    "pending_no_action": "No Action",
    "confirm_topup_title": "Confirmation",
    "topup_cb_transaction_id": "TRANSACTION ID",
    "topup_cb_manilla_ref": "REFRENCE ID",
    "topup_cb_amount": "AMOUNT",
    "topup_cb_chanel": "CHANNEL USED",
    "topup_cb_status": "STATUS",
    "admin_pass_reset_successful":"A new password has been generated and sent to ",
    "admin_pass_reset_failed":"Failed to reset password.",
    "pay_details_charge_label":"EXTRA CHARGES",
    "insufficient_balance": "Sorry you account balance is low. Kindly topup to proceed.",
}

"""
Application response codes
"""
CODES = {
    "FAIL": "01",
    "SUCCESS": "00",
    "ERROR": "02",
}


"""
Menu Styles
"""
STYLE = {
    "home_style":{"home":"color:#FF6A13; font-size:14px"},
    "bulkpay_style":{"bulkpay":"color:#FF6A13"},
    "dashboard_style":{"dashboard":"color:#FF6A13"},
    "trans_style":{"transactions":"color:#FF6A13"},
    "admins_style":{"admins":"color:#FF6A13; font-size:14px"},
    "validators_style":{"validators":"color:#FF6A13; font-size:14px"},
    "inst_style":{"inst":"color:#FF6A13"},
    "mer_style":{"mer":"color:#FF6A13; font-size:14px"},
    "logs_style":{"logs":"color:#FF6A13; font-size:14px"},
    "settings_style":{"settings":"color:#FF6A13"},
    "account_style":{"account":"color:#FF6A13"},
    "tup_style":{"topups":"color:#FF6A13"},
}
